Import('dspEnv')

controllerFunctions = dspEnv.StaticLibrary('controllerFunctions',[
                                                                'arm_pid_init_f32.c',
                                                                'arm_pid_init_q15.c',
                                                                'arm_pid_init_q31.c',
                                                                'arm_pid_reset_f32.c',
                                                                'arm_pid_reset_q15.c',
                                                                'arm_pid_reset_q31.c',
                                                                'arm_sin_cos_f32.c',
                                                                'arm_sin_cos_q31.c',
                                                               ])

dspEnv.Install('#lib/',controllerFunctions)

