Import('dspEnv')

fastMath = dspEnv.StaticLibrary('fastMath',[
                                            'arm_cos_f32.c',
                                            'arm_cos_q15.c',
                                            'arm_cos_q31.c',
                                            'arm_sin_f32.c',
                                            'arm_sin_q15.c',
                                            'arm_sin_q31.c',
                                            'arm_sqrt_q15.c',
                                            'arm_sqrt_q31.c',
                                        ])

dspEnv.Install('#lib/',fastMath)

