Import('env')

env.BuildModules([
                    'BasicMathFunctions',
                    'CommonTables',
                    'ComplexMathFunctions',
                    'ControllerFunctions',
                    'FastMathFunctions',
                    'FilteringFunctions',
                    'MatrixFunctions',
                    'StatisticsFunctions',
                    'SupportFunctions',
                    'TransformFunctions'
                 ])
