Import('env')

dspEnv = env.Clone()

dspEnv.Append(CPPDEFINES = [
    'ARM_MATH_CM4'
])

Export('dspEnv')

dspEnv.BuildModules([
                    'BasicMathFunctions',
                    'CommonTables',
                    'ComplexMathFunctions',
                    'ControllerFunctions',
                    'FastMathFunctions',
                    'FilteringFunctions',
                    'MatrixFunctions',
                    'StatisticsFunctions',
                    'SupportFunctions',
                    'TransformFunctions'
                 ])
