Import('env')

env.BuildModules([
                    'peripherals',
                    #'usb',
                    'dsp',
                    'applications',
                    'sys'
                 ])


