Import('dspEnv')

transforms = dspEnv.StaticLibrary('transforms',[
                                                'arm_cfft_radix4_f32.c',
                                                'arm_cfft_radix4_init_f32.c',
                                                'arm_cfft_radix4_init_q15.c',
                                                'arm_cfft_radix4_init_q31.c',
                                                'arm_cfft_radix4_q15.c',
                                                'arm_cfft_radix4_q31.c',
                                                'arm_dct4_f32.c',
                                                'arm_dct4_init_f32.c',
                                                'arm_dct4_init_q15.c',
                                                'arm_dct4_init_q31.c',
                                                'arm_dct4_q15.c',
                                                'arm_dct4_q31.c',
                                                'arm_rfft_f32.c',
                                                'arm_rfft_init_f32.c',
                                                'arm_rfft_init_q15.c',
                                                'arm_rfft_init_q31.c',
                                                'arm_rfft_q15.c',
                                                'arm_rfft_q31.c',
                                            ])

dspEnv.Install('#lib/',transforms)

