Import('env')

appEnv = env.Clone()

appEnv.Append(CPPPATH = [
    '#src/applications/helloWorld/',
    ])

helloWorld = appEnv.Program(
    target = 'helloWorld',
    source = [
        'main.c',
        'stm32f4xx_it.c',
        ],
    LIBS = ['peripherals', 'sysUtils']
    )
    
appEnv.Install('#bin/',appEnv.Objcopy(helloWorld))

